name: Deploy test-scaffold-2

on:
  push:
    branches: main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  HUMCTL_VERSION: '0.25.0'
  APP_NAME: test-scaffold-2
  CONTAINER_REGISTRY: docker.io
  IMAGE: stefanprodan/podinfo
  TAG: latest
  K8S_RESDEF: aws-quickstart


jobs:
  deploy:
    name: Build & Notify Humanitec
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}

      - name: Inform Humanitec
        run: |-
          humctl create artefact-version \
            --token ${{ secrets.HUMANITEC_TOKEN }} \
            --org ${{ vars.HUMANITEC_ORG_ID }} \
            -t container \
            -n ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE }} \
            --version ${{ env.TAG }} \
            --ref $GITHUB_REF \
            --commit $GITHUB_SHA

      - name: Create app
        run: |
          humctl create app ${{ env.APP_NAME }} \
           --token ${{ secrets.HUMANITEC_TOKEN }} \
           --org ${{ vars.HUMANITEC_ORG_ID }} \

      - name: Create matching criteria
        run: |
          export CRITERIA_ID=$(humctl api post --token ${{ secrets.HUMANITEC_TOKEN }} --org ${{ vars.HUMANITEC_ORG_ID }} /orgs/${{ vars.HUMANITEC_ORG_ID }}/resources/defs/${{ env.K8S_RESDEF }}/criteria \
            -d '{
            "app_id": "'${{ env.APP_NAME }}'"
          }' | jq --raw-output '.id' )
          echo $CRITERIA_ID

      - name: Deploy using Score
        run: |
          humctl score deploy \
            --token ${{ secrets.HUMANITEC_TOKEN }} \
            --org ${{ vars.HUMANITEC_ORG_ID }} \
            --app ${{ env.APP_NAME }} \
            --env development \
            -f score.yaml \
            --extensions humanitec.score.yaml \
            --workload-source-url "https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/score.yaml" \
            --image ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }} \
            --message "${{ github.event.head_commit.message }}"

